name: example
description: Example.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  mno_lcp:
    path: ../
  mno_shared:
    path: ../../shared

dependency_overrides:
  intl: ^0.19.0 # multiple_localization 0.3.0 requires intl 0.17.0
  meta: ^1.16.0
  collection: ^1.19.1
